# Generated by Django 6.0.1 on 2026-05-11 08:45

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0003_client_archived_at_client_deleted_at_and_more'),
        ('planning', '0004_intervention_archived_at_intervention_deleted_at_and_more'),
        ('referentiels', '0003_alter_referentiel_categorie'),
        ('stock', '0006_piece_archived_at_piece_deleted_at_piece_is_archived_and_more'),
        ('vehicules', '0003_vehicule_archived_at_vehicule_deleted_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdreReparation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, help_text="L'élément est dans la corbeille (suppression douce)", verbose_name='En corbeille')),
                ('deleted_at', models.DateTimeField(blank=True, help_text="Date à laquelle l'élément a été mis en corbeille", null=True, verbose_name='Date de mise en corbeille')),
                ('is_archived', models.BooleanField(default=False, help_text="L'élément est archivé (caché des vues principales)", verbose_name='Archivé')),
                ('archived_at', models.DateTimeField(blank=True, help_text="Date à laquelle l'élément a été archivé", null=True, verbose_name="Date d'archivage")),
                ('numero', models.CharField(editable=False, help_text='Format OR-AAAA-0001, reset chaque année', max_length=20, unique=True)),
                ('date_ouverture', models.DateField(default=datetime.date.today, help_text="Date de création de l'OR")),
                ('statut', models.CharField(choices=[('OUVERT', 'Ouvert'), ('EN_COURS', 'En cours'), ('CLOTURE', 'Clôturé'), ('ANNULE', 'Annulé')], default='OUVERT', max_length=20)),
                ('kilometrage_entree', models.PositiveIntegerField(blank=True, help_text="Km ou heures moteur à l'entrée", null=True)),
                ('description_travaux', models.TextField(blank=True, help_text='Description initiale (peut venir du motif du RDV)')),
                ('date_cloture', models.DateField(blank=True, null=True)),
                ('kilometrage_sortie', models.PositiveIntegerField(blank=True, null=True)),
                ('heure_sortie', models.TimeField(blank=True, null=True)),
                ('notes_internes', models.TextField(blank=True, help_text="Notes du mécanicien, non imprimées sur l'OR")),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordres_reparation', to='clients.client')),
                ('rdv', models.ForeignKey(blank=True, help_text="RDV qui a généré l'OR (optionnel)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordres_reparation', to='planning.intervention')),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordres_reparation', to='vehicules.vehicule')),
            ],
            options={
                'verbose_name': 'Ordre de réparation',
                'verbose_name_plural': 'Ordres de réparation',
                'ordering': ['-date_ouverture', '-numero'],
            },
        ),
        migrations.CreateModel(
            name='LignePieceUtilisee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('designation_snapshot', models.CharField(help_text='Désignation au moment de la sortie', max_length=200)),
                ('reference_snapshot', models.CharField(blank=True, help_text='Référence au moment de la sortie', max_length=100)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('piece', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='utilisations_or', to='stock.piece')),
                ('ordre_reparation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces', to='ordres_reparation.ordrereparation')),
            ],
            options={
                'verbose_name': 'Pièce utilisée (OR)',
                'verbose_name_plural': 'Pièces utilisées (OR)',
                'ordering': ['cree_le'],
            },
        ),
        migrations.CreateModel(
            name='LigneIntervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, help_text='Date à laquelle cette tâche a été effectuée')),
                ('duree_minutes', models.PositiveIntegerField(help_text='Durée en minutes (ex: 90 pour 1h30)')),
                ('detail', models.TextField(blank=True, help_text='Détail / notes sur cette intervention')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('mecanicien', models.ForeignKey(help_text='Mécanicien qui a effectué la tâche', on_delete=django.db.models.deletion.PROTECT, related_name='lignes_or_intervention', to='planning.collaborateur')),
                ('type_intervention', models.ForeignKey(help_text="Type d'intervention (depuis les Référentiels)", limit_choices_to={'categorie': 'TYPE_INTERVENTION'}, on_delete=django.db.models.deletion.PROTECT, related_name='lignes_or_intervention', to='referentiels.referentiel')),
                ('ordre_reparation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to='ordres_reparation.ordrereparation')),
            ],
            options={
                'verbose_name': 'Intervention (OR)',
                'verbose_name_plural': 'Interventions (OR)',
                'ordering': ['date', 'cree_le'],
            },
        ),
    ]
