# Generated by Django 6.0.1 on 2026-05-11 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordres_reparation', '0001_initial'),
        ('referentiels', '0004_typeintervention'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ligneintervention',
            name='type_intervention',
            field=models.ForeignKey(help_text="Type d'intervention (depuis les Référentiels)", limit_choices_to={'categorie': 'TYPE_INTERVENTION'}, on_delete=django.db.models.deletion.PROTECT, related_name='lignes_or_intervention', to='referentiels.typeintervention'),
        ),
    ]
