# Generated by Django 6.0.1 on 2026-05-11 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordres_reparation', '0002_alter_ligneintervention_type_intervention'),
        ('referentiels', '0004_typeintervention'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ligneintervention',
            name='type_intervention',
            field=models.ForeignKey(help_text="Type d'intervention (depuis les Référentiels)", on_delete=django.db.models.deletion.PROTECT, related_name='lignes_or_intervention', to='referentiels.referentiel'),
        ),
    ]
