# Generated by Django 6.0.1 on 2026-05-11 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordres_reparation', '0003_alter_ligneintervention_type_intervention'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lignepieceutilisee',
            name='designation_snapshot',
            field=models.CharField(blank=True, help_text='Auto-rempli au moment de la sortie (ne pas saisir)', max_length=200),
        ),
        migrations.AlterField(
            model_name='lignepieceutilisee',
            name='reference_snapshot',
            field=models.CharField(blank=True, help_text='Auto-rempli au moment de la sortie (ne pas saisir)', max_length=100),
        ),
    ]
