# Generated by Django 6.0.1 on 2026-06-07 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordres_reparation', '0006_alter_ordrereparation_archived_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordrereparation',
            name='cree_le',
        ),
        migrations.RemoveField(
            model_name='ordrereparation',
            name='modifie_le',
        ),
    ]
