# Generated by Django 6.0.1 on 2026-03-30 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0002_client_adresse'),
        ('planning', '0002_departement_collaborateur'),
        ('stock', '0002_piece_stock_suspendu'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametresFacturation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tva_pourcentage', models.DecimalField(decimal_places=2, default=20.0, help_text='Taux de TVA en % (ex: 20.00 pour 20%)', max_digits=5)),
                ('numero_devis_actuel', models.IntegerField(default=1, help_text='Compteur auto-incrémenté pour les numéros de devis')),
                ('numero_facture_actuel', models.IntegerField(default=1, help_text='Compteur auto-incrémenté pour les numéros de factures')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paramètres Facturation',
                'verbose_name_plural': 'Paramètres Facturation',
            },
        ),
        migrations.CreateModel(
            name='Devis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, help_text='Généré automatiquement : DEV-YY-NNNNN', max_length=20, unique=True)),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('date_validite', models.DateField(help_text="Date d'expiration du devis (au-delà → EXPIRE)")),
                ('montant_ht', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tva', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('montant_ttc', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('statut', models.CharField(choices=[('CREE', 'Créé'), ('VALIDE', 'Validé par client'), ('REFUSE', 'Refusé par client'), ('EXPIRE', 'Expiré'), ('FACTURE', 'Devenu facture')], default='CREE', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(help_text='Client concerné par ce devis', on_delete=django.db.models.deletion.CASCADE, related_name='devis', to='clients.client')),
                ('intervention', models.ForeignKey(blank=True, help_text='Intervention liée (optionnel)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devis', to='planning.intervention')),
            ],
            options={
                'verbose_name': 'Devis',
                'verbose_name_plural': 'Devis',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, help_text='Généré automatiquement : FAC-YY-NNNNN', max_length=20, unique=True)),
                ('date_emission', models.DateField(auto_now_add=True)),
                ('date_echeance', models.DateField(help_text='Date à laquelle le paiement est attendu')),
                ('montant_ht', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tva', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('montant_ttc', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('montant_paye', models.DecimalField(decimal_places=2, default=0, help_text='Montant déjà encaissé', max_digits=10)),
                ('statut', models.CharField(choices=[('EMISE', 'Émise'), ('PAYEE', 'Payée'), ('IMPAYEE', 'Impayée'), ('PARTIELLEMENT_PAYEE', 'Partiellement payée')], default='EMISE', max_length=25)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='clients.client')),
                ('devis', models.ForeignKey(blank=True, help_text="Devis d'origine (optionnel si facture directe)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures', to='factures.devis')),
                ('intervention', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures', to='planning.intervention')),
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': 'Factures',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LigneDevis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='Nom de la pièce ou description du service', max_length=255)),
                ('quantite', models.IntegerField(default=1)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('devis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes_devis', to='factures.devis')),
                ('piece', models.ForeignKey(blank=True, help_text="Laisser vide pour une ligne de service / main-d'œuvre libre", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lignes_devis', to='stock.piece')),
            ],
            options={
                'verbose_name': 'Ligne Devis',
                'verbose_name_plural': 'Lignes Devis',
            },
        ),
        migrations.CreateModel(
            name='LigneFacture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('quantite', models.IntegerField(default=1)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes_facture', to='factures.facture')),
                ('piece', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lignes_facture', to='stock.piece')),
            ],
            options={
                'verbose_name': 'Ligne Facture',
                'verbose_name_plural': 'Lignes Facture',
            },
        ),
    ]
