# Generated by Django 6.0.1 on 2026-05-02 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factures', '0002_add_forfait_intervention'),
    ]

    operations = [
        migrations.AddField(
            model_name='devis',
            name='archived_at',
            field=models.DateTimeField(blank=True, help_text="Date à laquelle l'élément a été archivé", null=True, verbose_name="Date d'archivage"),
        ),
        migrations.AddField(
            model_name='devis',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text="Date à laquelle l'élément a été mis en corbeille", null=True, verbose_name='Date de mise en corbeille'),
        ),
        migrations.AddField(
            model_name='devis',
            name='is_archived',
            field=models.BooleanField(default=False, help_text="L'élément est archivé (caché des vues principales)", verbose_name='Archivé'),
        ),
        migrations.AddField(
            model_name='devis',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text="L'élément est dans la corbeille (suppression douce)", verbose_name='En corbeille'),
        ),
        migrations.AddField(
            model_name='facture',
            name='archived_at',
            field=models.DateTimeField(blank=True, help_text="Date à laquelle l'élément a été archivé", null=True, verbose_name="Date d'archivage"),
        ),
        migrations.AddField(
            model_name='facture',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text="Date à laquelle l'élément a été mis en corbeille", null=True, verbose_name='Date de mise en corbeille'),
        ),
        migrations.AddField(
            model_name='facture',
            name='is_archived',
            field=models.BooleanField(default=False, help_text="L'élément est archivé (caché des vues principales)", verbose_name='Archivé'),
        ),
        migrations.AddField(
            model_name='facture',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text="L'élément est dans la corbeille (suppression douce)", verbose_name='En corbeille'),
        ),
    ]
