# Generated by Django 6.0.1 on 2026-05-16 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factures', '0003_devis_archived_at_devis_deleted_at_devis_is_archived_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametresfacturation',
            name='adresse_garage',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='parametresfacturation',
            name='email_garage',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='parametresfacturation',
            name='nom_garage',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='parametresfacturation',
            name='numero_tva',
            field=models.CharField(blank=True, default='', help_text='Numéro TVA intracommunautaire (ex: FR12345678900)', max_length=20),
        ),
        migrations.AddField(
            model_name='parametresfacturation',
            name='siret',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='parametresfacturation',
            name='telephone_garage',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
