# Generated by Django 6.0.1 on 2026-06-07 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factures', '0004_parametresfacturation_adresse_garage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devis',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date d'archivage"),
        ),
        migrations.AlterField(
            model_name='devis',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de mise en corbeille'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date d'archivage"),
        ),
        migrations.AlterField(
            model_name='facture',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de mise en corbeille'),
        ),
    ]
