# Generated by Django 6.0.1 on 2026-03-30 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='stock_suspendu',
            field=models.IntegerField(default=0, help_text='Quantité réservée pour des devis en cours (non encore facturés)'),
        ),
    ]
