# Generated by Django 6.0.1 on 2026-04-04 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_piece_fournisseur_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piece',
            name='fournisseur',
            field=models.CharField(blank=True, help_text='Nom du fournisseur (ancien champ texte — utiliser fournisseur_ref)', max_length=200),
        ),
    ]
