# Generated by Django 6.0.1 on 2026-06-07 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0008_alter_piece_archived_at_alter_piece_deleted_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='piece',
            name='date_creation',
        ),
        migrations.RemoveField(
            model_name='piece',
            name='date_modification',
        ),
    ]
