# Generated by Django 6.0.1 on 2026-03-14 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Referentiel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(choices=[('TYPE_VEHICULE', 'Types de véhicules'), ('TYPE_INTERVENTION', "Types d'interventions"), ('CATEGORIE_STOCK', 'Catégories de stock')], help_text='Catégorie du référentiel', max_length=30)),
                ('valeur', models.CharField(help_text='Clé interne (ex: VOITURE, BATEAU)', max_length=50)),
                ('label', models.CharField(help_text='Libellé affiché (ex: Voiture, Bateau)', max_length=100)),
                ('icone', models.CharField(blank=True, default='', help_text='Icône emoji (ex: 🚗)', max_length=10)),
                ('couleur', models.CharField(blank=True, default='', help_text='Couleur hex (ex: #2980b9)', max_length=20)),
                ('ordre', models.IntegerField(default=0, help_text="Ordre d'affichage")),
                ('actif', models.BooleanField(default=True, help_text='Visible dans les listes si True')),
            ],
            options={
                'verbose_name': 'Référentiel',
                'verbose_name_plural': 'Référentiels',
                'ordering': ['categorie', 'ordre', 'label'],
                'unique_together': {('categorie', 'valeur')},
            },
        ),
    ]
