# Generated by Django 6.0.1 on 2026-04-05 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referentiels', '0002_donnees_defaut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referentiel',
            name='categorie',
            field=models.CharField(choices=[('TYPE_VEHICULE', 'Types de véhicules'), ('TYPE_INTERVENTION', "Types d'interventions"), ('CATEGORIE_STOCK', 'Catégories de stock'), ('CATEGORIE_FOURNISSEUR', 'Catégories de fournisseurs')], help_text='Catégorie du référentiel', max_length=30),
        ),
    ]
