# Generated by Django 6.0.1 on 2026-05-11 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referentiels', '0003_alter_referentiel_categorie'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeIntervention',
            fields=[
                ('referentiel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='referentiels.referentiel')),
            ],
            bases=('referentiels.referentiel',),
        ),
    ]
