# Generated by Django 6.0.1 on 2026-03-30 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_adresse'),
        ('planning', '0002_departement_collaborateur'),
        ('vehicules', '0002_vehicule_type_vehicule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborateur',
            name='actif',
            field=models.BooleanField(default=True, help_text="Si désactivé, ce collaborateur n'apparaît plus dans les plannings"),
        ),
        migrations.AlterField(
            model_name='collaborateur',
            name='couleur',
            field=models.CharField(default='#27ae60', help_text='Couleur hex affichée dans le planning, ex: #27ae60', max_length=7),
        ),
        migrations.AlterField(
            model_name='collaborateur',
            name='nom',
            field=models.CharField(help_text='Nom complet du collaborateur, ex: Thomas Dupont', max_length=100),
        ),
        migrations.AlterField(
            model_name='collaborateur',
            name='role',
            field=models.CharField(blank=True, help_text='Rôle dans le garage, ex: Mécanicien, Formateur', max_length=100),
        ),
        migrations.AlterField(
            model_name='departement',
            name='actif',
            field=models.BooleanField(default=True, help_text="Si désactivé, ce département n'apparaît plus dans les formulaires"),
        ),
        migrations.AlterField(
            model_name='departement',
            name='couleur',
            field=models.CharField(default='#2980b9', help_text='Couleur hex affichée dans le planning, ex: #2980b9', max_length=7),
        ),
        migrations.AlterField(
            model_name='departement',
            name='nom',
            field=models.CharField(help_text="Nom affiché dans l'interface, ex: Atelier, Académie", max_length=100),
        ),
        migrations.AlterField(
            model_name='departement',
            name='ordre',
            field=models.PositiveIntegerField(default=0, help_text="Ordre d'affichage (0 = en premier)"),
        ),
        migrations.AlterField(
            model_name='departement',
            name='requiert_vehicule',
            field=models.BooleanField(default=True, help_text='Si True, le champ véhicule est demandé dans le formulaire de RDV'),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to='clients.client'),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='date_debut',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='date_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='date_modification',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='departement',
            field=models.ForeignKey(blank=True, help_text='Département concerné (ex: Atelier, Académie)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='interventions', to='planning.departement'),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='rappel_envoye',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='statut',
            field=models.CharField(choices=[('PLANIFIE', 'Planifié'), ('EN_COURS', 'En cours'), ('TERMINE', 'Terminé'), ('ANNULE', 'Annulé')], default='PLANIFIE', max_length=20),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='vehicule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to='vehicules.vehicule'),
        ),
    ]
