# Generated by Django 6.0.1 on 2026-02-04 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandeFournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_commande', models.CharField(help_text='Numéro de commande (ex: CMD-2026-001)', max_length=50, unique=True)),
                ('fournisseur', models.CharField(help_text='Nom du fournisseur', max_length=200)),
                ('date_commande', models.DateField(help_text='Date de la commande')),
                ('date_livraison_prevue', models.DateField(blank=True, help_text='Date de livraison prévue', null=True)),
                ('date_livraison_reelle', models.DateField(blank=True, help_text='Date de livraison réelle', null=True)),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('ENVOYEE', 'Envoyée'), ('EN_ATTENTE', 'En attente de livraison'), ('LIVREE', 'Livrée'), ('ANNULEE', 'Annulée')], default='BROUILLON', help_text='État de la commande', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Notes ou commentaires sur la commande')),
                ('date_creation', models.DateTimeField(auto_now_add=True, help_text='Date de création de la commande')),
                ('date_modification', models.DateTimeField(auto_now=True, help_text='Dernière modification')),
            ],
            options={
                'verbose_name': 'Commande Fournisseur',
                'verbose_name_plural': 'Commandes Fournisseurs',
                'ordering': ['-date_commande'],
            },
        ),
        migrations.CreateModel(
            name='LigneCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField(default=1, help_text='Quantité commandée')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, help_text='Prix unitaire au moment de la commande', max_digits=10)),
                ('commande', models.ForeignKey(help_text='Commande à laquelle appartient cette ligne', on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='fournisseurs.commandefournisseur')),
                ('piece', models.ForeignKey(help_text='Pièce commandée', on_delete=django.db.models.deletion.CASCADE, to='stock.piece')),
            ],
            options={
                'verbose_name': 'Ligne de commande',
                'verbose_name_plural': 'Lignes de commande',
            },
        ),
    ]
