# Generated by Django 6.0.1 on 2026-02-04 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(help_text='Référence unique de la pièce (ex: FLT-OIL-001)', max_length=50, unique=True)),
                ('nom', models.CharField(help_text='Nom de la pièce (ex: Filtre à huile)', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description détaillée (compatibilité, specs, etc.)')),
                ('categorie', models.CharField(choices=[('FILTRATION', 'Filtration'), ('HUILES', 'Huiles & Liquides'), ('FREINAGE', 'Freinage'), ('PNEUMATIQUE', 'Pneumatiques'), ('ELECTRICITE', 'Électricité'), ('MECANIQUE', 'Mécanique'), ('CARROSSERIE', 'Carrosserie'), ('AUTRE', 'Autre')], default='AUTRE', help_text='Catégorie de la pièce', max_length=20)),
                ('prix_achat', models.DecimalField(decimal_places=2, help_text="Prix d'achat HT chez le fournisseur", max_digits=10)),
                ('prix_vente', models.DecimalField(decimal_places=2, help_text='Prix de vente TTC au client', max_digits=10)),
                ('stock_actuel', models.IntegerField(default=0, help_text='Quantité actuellement en stock')),
                ('stock_minimum', models.IntegerField(default=5, help_text="Seuil d'alerte (si stock < seuil → alerte)")),
                ('fournisseur', models.CharField(blank=True, help_text='Nom du fournisseur principal', max_length=200)),
                ('delai_livraison', models.IntegerField(default=2, help_text='Délai de livraison en jours')),
                ('date_creation', models.DateTimeField(auto_now_add=True, help_text="Date d'ajout de la pièce dans le système")),
                ('date_modification', models.DateTimeField(auto_now=True, help_text='Dernière modification')),
            ],
            options={
                'verbose_name': 'Pièce',
                'verbose_name_plural': 'Pièces',
                'ordering': ['categorie', 'nom'],
            },
        ),
    ]
