# Generated by Django 6.0.1 on 2026-04-04 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_alter_piece_fournisseur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='piece',
            name='fournisseur',
        ),
    ]
