# Generated by Django 6.0.1 on 2026-05-02 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fournisseurs', '0004_fournisseur_archived_at_fournisseur_deleted_at_and_more'),
        ('stock', '0005_remove_piece_fournisseur'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='archived_at',
            field=models.DateTimeField(blank=True, help_text="Date à laquelle l'élément a été archivé", null=True, verbose_name="Date d'archivage"),
        ),
        migrations.AddField(
            model_name='piece',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text="Date à laquelle l'élément a été mis en corbeille", null=True, verbose_name='Date de mise en corbeille'),
        ),
        migrations.AddField(
            model_name='piece',
            name='is_archived',
            field=models.BooleanField(default=False, help_text="L'élément est archivé (caché des vues principales)", verbose_name='Archivé'),
        ),
        migrations.AddField(
            model_name='piece',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text="L'élément est dans la corbeille (suppression douce)", verbose_name='En corbeille'),
        ),
        migrations.AlterField(
            model_name='piece',
            name='categorie',
            field=models.CharField(choices=[('FILTRATION', 'Filtration'), ('HUILES', 'Huiles & Liquides'), ('FREINAGE', 'Freinage'), ('PNEUMATIQUE', 'Pneumatiques'), ('ELECTRICITE', 'Électricité'), ('MECANIQUE', 'Mécanique'), ('CARROSSERIE', 'Carrosserie'), ('AUTRE', 'Autre')], default='AUTRE', max_length=20),
        ),
        migrations.AlterField(
            model_name='piece',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='piece',
            name='date_modification',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='piece',
            name='delai_livraison',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='piece',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='piece',
            name='fournisseur_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pieces', to='fournisseurs.fournisseur'),
        ),
        migrations.AlterField(
            model_name='piece',
            name='nom',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='piece',
            name='prix_achat',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='piece',
            name='prix_vente',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='piece',
            name='stock_actuel',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='piece',
            name='stock_minimum',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='piece',
            name='stock_suspendu',
            field=models.IntegerField(default=0, help_text='Quantité réservée pour des devis en cours'),
        ),
    ]
