# Generated by Django 6.0.1 on 2026-02-04 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Nom de famille du client', max_length=100)),
                ('prenom', models.CharField(blank=True, help_text='Prénom du client', max_length=100)),
                ('telephone', models.CharField(blank=True, help_text='Numéro de téléphone', max_length=20)),
                ('email', models.EmailField(blank=True, help_text='Email du client', max_length=254)),
                ('date_creation', models.DateTimeField(auto_now_add=True, help_text='Date de création de la fiche client')),
                ('notes', models.TextField(blank=True, help_text='Notes sur le client (ex: préfère être appelé le matin)')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['nom', 'prenom'],
            },
        ),
    ]
