# Generated by Django 6.0.1 on 2026-02-20 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='adresse',
            field=models.CharField(blank=True, help_text='Adresse postale complète', max_length=255),
        ),
    ]
