# Generated by Django 6.0.1 on 2026-06-07 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_client_created_at_client_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='date_creation',
        ),
    ]
