# Generated by Django 6.0.1 on 2026-06-07 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_remove_client_date_creation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date d'archivage"),
        ),
        migrations.AlterField(
            model_name='client',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de mise en corbeille'),
        ),
    ]
