# Generated by Django 6.0.1 on 2026-02-04 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immatriculation', models.CharField(help_text="Plaque d'immatriculation (ex: AB-123-CD)", max_length=20, unique=True)),
                ('marque', models.CharField(help_text='Marque du véhicule (ex: Peugeot, Renault)', max_length=50)),
                ('modele', models.CharField(help_text='Modèle du véhicule (ex: 308, Clio)', max_length=50)),
                ('annee', models.IntegerField(blank=True, help_text='Année de mise en circulation', null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True, help_text="Date d'ajout du véhicule dans la base")),
                ('notes', models.TextField(blank=True, help_text="Notes sur le véhicule (ex: pneus neige l'hiver)")),
                ('proprietaire', models.ForeignKey(blank=True, help_text='Propriétaire actuel du véhicule', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicules', to='clients.client')),
            ],
            options={
                'verbose_name': 'Véhicule',
                'verbose_name_plural': 'Véhicules',
                'ordering': ['marque', 'modele'],
            },
        ),
    ]
