# Generated by Django 6.0.1 on 2026-03-12 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicule',
            name='type_vehicule',
            field=models.CharField(choices=[('VOITURE', 'Voiture'), ('MOTO', 'Moto'), ('MOTOCULTURE', 'Motoculture'), ('BATEAU', 'Bateau')], default='VOITURE', help_text='Type de véhicule (Voiture, Moto, Motoculture, Bateau)', max_length=20),
        ),
    ]
