# Generated by Django 6.0.1 on 2026-05-02 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_adresse'),
        ('vehicules', '0002_vehicule_type_vehicule'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicule',
            name='archived_at',
            field=models.DateTimeField(blank=True, help_text="Date à laquelle l'élément a été archivé", null=True, verbose_name="Date d'archivage"),
        ),
        migrations.AddField(
            model_name='vehicule',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text="Date à laquelle l'élément a été mis en corbeille", null=True, verbose_name='Date de mise en corbeille'),
        ),
        migrations.AddField(
            model_name='vehicule',
            name='is_archived',
            field=models.BooleanField(default=False, help_text="L'élément est archivé (caché des vues principales)", verbose_name='Archivé'),
        ),
        migrations.AddField(
            model_name='vehicule',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text="L'élément est dans la corbeille (suppression douce)", verbose_name='En corbeille'),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='annee',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='marque',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='modele',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='proprietaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicules', to='clients.client'),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='type_vehicule',
            field=models.CharField(choices=[('VOITURE', 'Voiture'), ('MOTO', 'Moto'), ('MOTOCULTURE', 'Motoculture'), ('BATEAU', 'Bateau')], default='VOITURE', max_length=20),
        ),
    ]
