# Generated by Django 6.0.1 on 2026-06-07 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicules', '0006_alter_vehicule_archived_at_alter_vehicule_deleted_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicule',
            name='date_creation',
        ),
    ]
