# Generated by Django 6.0.1 on 2026-01-26 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Nom de famille du client', max_length=100)),
                ('prenom', models.CharField(blank=True, help_text='Prénom du client', max_length=100)),
                ('telephone', models.CharField(blank=True, help_text='Numéro de téléphone', max_length=20)),
                ('email', models.EmailField(blank=True, help_text='Email du client', max_length=254)),
                ('date_creation', models.DateTimeField(auto_now_add=True, help_text='Date de création de la fiche client')),
                ('notes', models.TextField(blank=True, help_text='Notes sur le client (ex: préfère être appelé le matin)')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immatriculation', models.CharField(help_text="Plaque d'immatriculation (ex: AB-123-CD)", max_length=20, unique=True)),
                ('marque', models.CharField(help_text='Marque du véhicule (ex: Peugeot, Renault)', max_length=50)),
                ('modele', models.CharField(help_text='Modèle du véhicule (ex: 308, Clio)', max_length=50)),
                ('annee', models.IntegerField(blank=True, help_text='Année de mise en circulation', null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True, help_text="Date d'ajout du véhicule dans la base")),
                ('notes', models.TextField(blank=True, help_text="Notes sur le véhicule (ex: pneus neige l'hiver)")),
                ('proprietaire', models.ForeignKey(blank=True, help_text='Propriétaire actuel du véhicule', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicules', to='core.client')),
            ],
            options={
                'verbose_name': 'Véhicule',
                'verbose_name_plural': 'Véhicules',
                'ordering': ['marque', 'modele'],
            },
        ),
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_rdv', models.CharField(choices=[('ATELIER', 'Atelier (Mécanique)'), ('ACADEMIE', 'Académie (Cours)')], default='ATELIER', help_text='Type de rendez-vous (Atelier ou Académie)', max_length=20)),
                ('date_debut', models.DateTimeField(help_text="Date et heure du début de l'intervention")),
                ('date_fin', models.DateTimeField(blank=True, help_text='Date et heure de fin (optionnel, peut être calculé)', null=True)),
                ('description', models.TextField(blank=True, help_text='Travaux à effectuer (ex: Vidange + filtre à huile)')),
                ('statut', models.CharField(choices=[('PLANIFIE', 'Planifié'), ('EN_COURS', 'En cours'), ('TERMINE', 'Terminé'), ('ANNULE', 'Annulé')], default='PLANIFIE', help_text="État actuel de l'intervention", max_length=20)),
                ('rappel_envoye', models.BooleanField(default=False, help_text='True si le rappel a déjà été envoyé')),
                ('date_creation', models.DateTimeField(auto_now_add=True, help_text='Date de création du rendez-vous')),
                ('date_modification', models.DateTimeField(auto_now=True, help_text='Dernière modification')),
                ('client', models.ForeignKey(help_text='Client concerné par cette intervention', on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to='core.client')),
                ('vehicule', models.ForeignKey(blank=True, help_text='Véhicule concerné par cette intervention', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to='core.vehicule')),
            ],
            options={
                'verbose_name': 'Intervention',
                'verbose_name_plural': 'Interventions',
                'ordering': ['-date_debut'],
            },
        ),
    ]
