# Generated by Django 6.0.1 on 2026-02-04 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('vehicules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_rdv', models.CharField(choices=[('ATELIER', 'Atelier (Mécanique)'), ('ACADEMIE', 'Académie (Cours)')], default='ATELIER', help_text='Type de rendez-vous (Atelier ou Académie)', max_length=20)),
                ('date_debut', models.DateTimeField(help_text="Date et heure du début de l'intervention")),
                ('date_fin', models.DateTimeField(blank=True, help_text='Date et heure de fin (optionnel, peut être calculé)', null=True)),
                ('description', models.TextField(blank=True, help_text='Travaux à effectuer (ex: Vidange + filtre à huile)')),
                ('statut', models.CharField(choices=[('PLANIFIE', 'Planifié'), ('EN_COURS', 'En cours'), ('TERMINE', 'Terminé'), ('ANNULE', 'Annulé')], default='PLANIFIE', help_text="État actuel de l'intervention", max_length=20)),
                ('rappel_envoye', models.BooleanField(default=False, help_text='True si le rappel a déjà été envoyé')),
                ('date_creation', models.DateTimeField(auto_now_add=True, help_text='Date de création du rendez-vous')),
                ('date_modification', models.DateTimeField(auto_now=True, help_text='Dernière modification')),
                ('client', models.ForeignKey(help_text='Client concerné par cette intervention', on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to='clients.client')),
                ('vehicule', models.ForeignKey(blank=True, help_text='Véhicule concerné par cette intervention', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to='vehicules.vehicule')),
            ],
            options={
                'verbose_name': 'Intervention',
                'verbose_name_plural': 'Interventions',
                'ordering': ['-date_debut'],
            },
        ),
    ]
