# Generated by Django 6.0.1 on 2026-05-16 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0004_intervention_archived_at_intervention_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervention',
            name='statut',
            field=models.CharField(choices=[('PLANIFIE', 'Planifié'), ('RECEPTIONNE', 'Réceptionné'), ('EN_COURS', 'En cours'), ('TERMINE', 'Terminé'), ('ANNULE', 'Annulé')], default='PLANIFIE', max_length=20),
        ),
    ]
