# Generated by Django 6.0.1 on 2026-04-05 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fournisseurs', '0002_fournisseur_categorie_favori'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fournisseur',
            name='categorie',
            field=models.CharField(blank=True, default='AUTRE', help_text='Catégorie du fournisseur — valeur libre, gérée via les Référentiels', max_length=50),
        ),
    ]
