# Generated by Django 6.0.1 on 2026-05-02 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fournisseurs', '0003_alter_fournisseur_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='fournisseur',
            name='archived_at',
            field=models.DateTimeField(blank=True, help_text="Date à laquelle l'élément a été archivé", null=True, verbose_name="Date d'archivage"),
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text="Date à laquelle l'élément a été mis en corbeille", null=True, verbose_name='Date de mise en corbeille'),
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='is_archived',
            field=models.BooleanField(default=False, help_text="L'élément est archivé (caché des vues principales)", verbose_name='Archivé'),
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text="L'élément est dans la corbeille (suppression douce)", verbose_name='En corbeille'),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='actif',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='adresse',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='categorie',
            field=models.CharField(blank=True, default='AUTRE', help_text='Catégorie du fournisseur — gérée via les Référentiels', max_length=50),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='contact_nom',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='date_modification',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='email',
            field=models.EmailField(help_text='Email principal pour les commandes', max_length=254),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='est_favori',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='telephone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
