# Generated by Django 6.0.1 on 2026-06-03 11:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "fournisseurs",
            "0004_fournisseur_archived_at_fournisseur_deleted_at_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="fournisseur",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                help_text="Rempli automatiquement à la création",
                verbose_name="Date de création",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="fournisseur",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Mis à jour automatiquement à chaque modification",
                verbose_name="Dernière modification",
            ),
        ),
    ]
