# Generated by Django 6.0.1 on 2026-06-07 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fournisseurs', '0006_alter_fournisseur_archived_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fournisseur',
            name='date_creation',
        ),
        migrations.RemoveField(
            model_name='fournisseur',
            name='date_modification',
        ),
    ]
